### ISSUE TITLE
Problem: Cannot compile on overleaf

### ISSUE THREAD

**Issue by jiadong5** [martinz2002/zjui-ece445-individual-template#1]
The problem is because of the package `fontspec`, the default compiler on overlaf is pdflatex, which is a compiler not supporting `fontspec`.
```
! Fatal Package fontspec Error: The fontspec package requires either XeTeX or
(fontspec)                      LuaTeX.
(fontspec)                      
(fontspec)                      You must change your typesetting engine to,
(fontspec)                      e.g., "xelatex" or "lualatex" instead of
(fontspec)                      "latex" or "pdflatex".
```
There is error like above.

The alternative way is to mod `ece445thesis.cls` line 35:

change from 
```
\RequirePackage{fontspec}
```
to
```
\RequirePackage{newpxtext}
```

Now it's like:
![image](https://github.com/martinz2002/zjui-ece445-individual-template/assets/83275455/2a0760cc-faee-4b10-9f4a-89371b53e012)

**Comment by martinz2002** [comment]
In order to apply Times fonts (newtx), the template uses `newtxtext` which internally calls `fontspec`. The `fontspec` package only supports XeLaTeX and LuaLaTeX. Switching to XeLaTeX on overleaf can resolve this issue.

For how to change compiler in Overleaf, see: [Changing compiler](https://www.overleaf.com/learn/how-to/Changing_compiler).

But you did remind me of some duplicately imported packages in the template. I do appreciate your feekdback.

Thank you.
